# ============================================================
# c206_content.py — เนื้อหาเช็กลิสต์ Cessna T206H
#
# ถอดจาก Cessna Pilot's Checklist, Model T206H
#   Original Issue 9 November 1998 · Revision 4 · 13 May 2002
#   P/N T206HCLUS04
#
# ⚠️ ต้นฉบับที่ได้มาเป็นภาพถ่ายที่ "ท้ายหน้าถูกตัด" เกือบทุกหน้า
#    รายการที่อยู่บรรทัดล่างสุดของแต่ละหน้าจึงหายไป จุดที่หายทำเครื่องหมายไว้
#    ด้วย GAP ในข้อมูลด้านล่าง และจะพิมพ์ออกมาเป็นแถบเตือนบนกระดาษ
#    ไม่ได้เดาหรือแต่งขึ้นเอง — เอกสารในห้องนักบินเดาไม่ได้
#
# ⚠️ ต้นฉบับเป็นของ T206H (เทอร์โบ TIO-540) ไม่ใช่ 206H ธรรมดา
#    ค่ากำลังเครื่องและ manifold pressure ของสองรุ่นไม่เท่ากัน
# ============================================================

GAP = '__GAP__'          # แถวเตือนว่าต้นฉบับขาด


def gap(what):
    return (GAP, what)


NORMAL = [
 ('AIRSPEEDS — NORMAL OPERATION (3,600 LB)', [
   ('Normal climb out', '75–85 KIAS'),
   ('Short field takeoff, flaps 20° — speed at 50 ft', '74 KIAS'),
   ('Enroute climb, flaps up — normal', '95 KIAS'),
   ('Best rate of climb, SL to 17,000 ft', '89 KIAS'),
   ('Best rate of climb, 24,000 ft', '79 KIAS'),
   ('Best angle of climb, sea level', '69 KIAS'),
   ('Best angle of climb, 10,000 ft', '72 KIAS'),
   ('Normal approach, flaps up', '80–90 KIAS'),
   ('Normal approach, flaps 40°', '70–80 KIAS'),
   ('Short field approach, flaps 40°', '67 KIAS'),
   ('Balked landing, max power, flaps 20°', '85 KIAS'),
   ('Turbulent air penetration — 3,600 / 2,950 / 2,300 lb', '125 / 120 / 106 KIAS'),
   ('Max demonstrated crosswind, takeoff or landing', '20 KNOTS'),
 ]),
 ('PREFLIGHT — 1 CABIN', [
   ('Pitot tube cover', 'REMOVE · CHECK FOR BLOCKAGE'),
   ("Pilot's Operating Handbook", 'AVAILABLE IN THE AIRPLANE'),
   ('Airplane weight and balance', 'CHECKED'),
   ('Parking brake', 'SET'),
   ('Control wheel lock', 'REMOVE'),
   ('Ignition switch', 'OFF'),
   ('Avionics master switch', 'OFF'),
   ('⚠ Treat propeller as if ignition were ON', 'STAND CLEAR OF ARC'),
   ('Master switch', 'ON'),
   ('Fuel quantity indicators · L LOW FUEL R annunciators', 'CHECK QTY · ENSURE EXTINGUISHED'),
   ('Avionics master switch', 'ON'),
   ('Avionics cooling fan', 'CHECK AUDIBLY'),
   ('Avionics master switch', 'OFF'),
   ('Static pressure alternate source valve', 'OFF'),
   ('Annunciator panel switch', 'HOLD IN TST · ALL ILLUMINATE'),
   ('Annunciator panel test switch', 'RELEASE · CHECK'),
   ('Fuel selector valve', 'BOTH'),
   ('Flaps', 'EXTEND'),
   ('Pitot heat', 'ON · WARM WITHIN 30 SEC'),
   ('Pitot heat', 'OFF'),
   ('Master switch', 'OFF'),
   ('Trim controls', 'NEUTRAL'),
   ('Oxygen supply pressure', 'CHECK'),
   ('Oxygen masks', 'CHECK'),
 ]),
 ('PREFLIGHT — 2 EMPENNAGE', [
   ('Rudder gust lock (if installed)', 'REMOVE'),
   ('Tail tie-down', 'DISCONNECT'),
   ('Control surfaces', 'FREE AND SECURE'),
   ('Trim tab', 'CHECK SECURITY'),
   ('Cargo doors (right side only)', 'SECURELY LATCHED'),
   ('Antennas', 'SECURE · CHECK CONDITION'),
 ]),
 ('PREFLIGHT — 3 RIGHT WING TRAILING EDGE', [
   ('Flap', 'SECURE · CHECK CONDITION'),
   ('Aileron', 'FREE AND SECURE'),
 ]),
 ('PREFLIGHT — 4 RIGHT WING', [
   ('Wing tie-down', 'DISCONNECT'),
   ('Fuel tank vent opening', 'CHECK FOR STOPPAGE'),
   ('Main wheel tire', 'INFLATION · CONDITION'),
   ('Fuel tank sump quick drain valves', 'DRAIN · SAMPLE CLEAR'),
   ('Fuel quantity', 'CHECK VISUALLY'),
   ('Fuel filler cap', 'SECURE · VENT UNOBSTRUCTED'),
 ]),
 ('PREFLIGHT — 5 NOSE', [
   ('Static source opening (right side)', 'CHECK FOR BLOCKAGE'),
   ('Fuel strainer quick drain valve', 'DRAIN · SAMPLE CLEAR'),
   ('Engine oil dipstick / filler cap', 'CHECK · MIN 6 QT · 11 QT EXTENDED'),
   ('Engine cooling air inlets · oil cooling inlet', 'CLEAR OF OBSTRUCTIONS'),
   ('Propeller and spinner', 'NO NICKS · SECURE'),
   ('Engine induction air filter', 'CHECK FOR RESTRICTION'),
   ('Nose wheel strut and tire', 'INFLATION · CONDITION'),
   ('Static source opening (left side)', 'CHECK FOR BLOCKAGE'),
 ]),
 ('PREFLIGHT — 6 LEFT WING', [
   ('Fuel quantity', 'CHECK VISUALLY'),
   ('Fuel filler cap', 'SECURE · VENT UNOBSTRUCTED'),
   ('Fuel tank sump quick drain valves', 'DRAIN · SAMPLE CLEAR'),
   ('Main wheel tire', 'INFLATION · CONDITION'),
 ]),
 ('PREFLIGHT — 7 LEFT WING LEADING EDGE', [
   ('Fuel tank vent opening', 'CHECK FOR BLOCKAGE'),
   ('Stall warning vane', 'FREE · HORN SOUNDS'),
   ('Wing tie-down', 'DISCONNECT'),
   ('Landing / taxi light(s)', 'CONDITION · CLEAN'),
 ]),
 ('PREFLIGHT — 8 LEFT WING TRAILING EDGE', [
   ('Aileron', 'FREE AND SECURE'),
   ('Flap', 'SECURE · CHECK CONDITION'),
 ]),
 ('BEFORE STARTING ENGINE', [
   ('Preflight inspection', 'COMPLETE'),
   ('Passenger briefing', 'COMPLETE'),
   ('Seats and seat belts', 'ADJUST AND LOCK'),
   gap('ข้อ 4 และ 5 — ท้ายหน้าต้นฉบับถูกตัด'),
   ('Electrical equipment', 'OFF'),
   ('Avionics master switch', 'OFF — REQUIRED BEFORE START'),
   ('Cowl flaps', 'OPEN'),
   ('Fuel selector valve', 'BOTH'),
   ('Avionics circuit breakers', 'CHECK IN'),
 ]),
 ('STARTING ENGINE (WITH BATTERY)', [
   ('Throttle', 'OPEN 1/4 INCH'),
   ('Propeller', 'HIGH RPM'),
   ('Mixture', 'IDLE CUT OFF'),
   ('Propeller area', 'CLEAR'),
   ('Master switch', 'ON'),
   ('Auxiliary fuel pump switch', 'ON  (omit 6–8 if engine warm)'),
   ('Mixture', 'FULL RICH UNTIL FLOW RISES · THEN IDLE CUT OFF'),
   ('Auxiliary fuel pump switch', 'OFF'),
   ('Ignition switch', 'START · RELEASE WHEN RUNNING'),
   ('Mixture', 'ADVANCE SMOOTHLY TO RICH'),
   ('Oil pressure', 'CHECK'),
   ('Flashing beacon and navigation lights', 'ON AS REQUIRED'),
   ('Avionics master switch', 'ON'),
   ('Radios', 'ON'),
 ]),
 ('STARTING ENGINE (WITH EXTERNAL POWER)', [
   ('Throttle', 'OPEN 1/4 INCH'),
   ('Propeller', 'HIGH RPM'),
   ('Mixture', 'IDLE CUT OFF'),
   ('Propeller area', 'CLEAR'),
   ('External power', 'CONNECT TO RECEPTACLE'),
   ('Master switch', 'ON'),
   ('Auxiliary fuel pump switch', 'ON  (omit 7–9 if engine warm)'),
   ('Mixture', 'FULL RICH UNTIL FLOW RISES · THEN IDLE CUT OFF'),
   ('Auxiliary fuel pump switch', 'OFF'),
   ('Ignition switch', 'START · RELEASE WHEN RUNNING'),
   ('Mixture', 'ADVANCE SMOOTHLY TO RICH'),
   ('Oil pressure', 'CHECK'),
   ('External power', 'DISCONNECT · SECURE DOOR'),
   ('Ammeter', 'CHECK'),
   ('Flashing beacon and navigation lights', 'ON AS REQUIRED'),
   ('Avionics master switch', 'ON'),
   ('Radios', 'ON'),
 ]),
 ('BEFORE TAKEOFF', [
   ('Parking brake', 'SET'),
   ('Passenger seats', 'AS FAR FORWARD AS PRACTICAL'),
   ('Passenger seat backs', 'MOST UPRIGHT POSITION'),
   ('Seats and seat belts', 'CHECK SECURE'),
   ('Cabin doors', 'CLOSED AND LOCKED'),
   ('Flight controls', 'FREE AND CORRECT'),
   ('Flight instruments', 'CHECK AND SET'),
   ('Fuel quantity', 'CHECK'),
   ('Auxiliary fuel pump', 'OFF'),
   ('Mixture', 'RICH'),
   ('Fuel selector valve', 'RECHECK BOTH'),
   ('Throttle', '1800 RPM'),
   gap('ข้อ 12.a (ตรวจแมกนีโตและค่า RPM drop ที่ยอมรับได้) — ท้ายหน้าต้นฉบับถูกตัด'),
   ('   b. Propeller', 'CYCLE HIGH–LOW–HIGH (FULL IN)'),
   ('   c. Vacuum gage', 'CHECK'),
   ('   d. Engine instruments and ammeter', 'CHECK'),
   ('   e. Annunciator panel', 'NO ANNUNCIATORS ILLUMINATED'),
   ('Throttle', 'CHECK IDLE'),
   ('Throttle', '1000 RPM'),
   ('Throttle friction lock', 'ADJUST'),
   ('Strobe lights', 'AS DESIRED'),
   ('Electric trim (if installed)', 'PREFLIGHT TEST'),
   ('Radios and avionics', 'SET'),
   ('NAV/GPS switch (if installed)', 'SET'),
   ('Autopilot (if installed)', 'OFF'),
   ('Elevator trim and rudder trim', 'SET FOR TAKEOFF'),
   ('Cowl flaps', 'OPEN'),
   ('Wing flaps', 'SET FOR TAKEOFF (0° TO 20°)'),
   ('Brakes', 'RELEASE'),
 ]),
 ('TAKEOFF — NORMAL', [
   ('Wing flaps', '0° – 20°'),
   ('Power', '39 IN. HG. AND 2500 RPM'),
   ('Mixture', 'ADJUST TO 34 GPH FUEL FLOW'),
   ('Elevator control', 'LIFT NOSE WHEEL AT 55 KIAS'),
   ('Climb speed', '75–85 KIAS (FLAPS 20°)'),
   ('Wing flaps', 'RETRACT AFTER OBSTACLES CLEARED'),
 ]),
 ('TAKEOFF — SHORT FIELD', [
   ('Wing flaps', '20°'),
   ('Brakes', 'APPLY'),
   ('Power', '39 IN. HG. AND 2500 RPM'),
   ('Mixture', 'ADJUST TO 34 GPH FUEL FLOW'),
   ('Brakes', 'RELEASE'),
   ('Elevator control', 'MAINTAIN SLIGHTLY TAIL LOW'),
   ('Climb speed', '74 KIAS UNTIL OBSTACLES CLEARED'),
   ('Wing flaps', 'RETRACT SLOWLY AFTER 90 KIAS'),
   ('Power', 'DO NOT REDUCE UNTIL FLAPS RETRACTED'),
 ]),
 ('ENROUTE CLIMB — NORMAL', [
   ('Airspeed', '95–105 KIAS'),
   ('Power', '30 IN. HG. AND 2400 RPM'),
   ('Mixture', 'LEAN TO 20 GPH FUEL FLOW'),
   ('Fuel selector valve', 'BOTH'),
   ('Cowl flaps', 'OPEN AS REQUIRED'),
 ]),
 ('ENROUTE CLIMB — MAXIMUM PERFORMANCE', [
   ('Airspeed', '89 KIAS'),
   ('Power', '39 IN. HG. AND 2500 RPM'),
   ('Mixture', 'ADJUST TO 34 GPH FUEL FLOW'),
   ('Fuel selector valve', 'BOTH'),
   ('Cowl flaps', 'OPEN'),
   ('Above 17,000 ft', 'SEE MIN FUEL FLOW PLACARD'),
 ]),
 ('CRUISE', [
   ('Power', '15–30 IN. HG. · 2000–2400 RPM (MAX 75%)'),
   ('Mixture', 'LEAN'),
   ('Elevator and rudder trim', 'ADJUST'),
   ('Cowl flaps', 'AS REQUIRED'),
   ('Auxiliary fuel pump', 'ON MOMENTARILY WHEN SWITCHING TANKS'),
 ]),
 ('DESCENT', [
   ('Power', 'AS DESIRED'),
   ('Mixture', 'ENRICHEN AS REQUIRED'),
   ('Cowl flaps', 'CLOSED'),
   ('Altimeter', 'SET'),
   ('NAV/GPS switch', 'SET'),
   ('Fuel selector valve', 'BOTH'),
   ('Wing flaps — serials thru T20608361', '0–10° <140 KIAS · 10–40° <100 KIAS'),
   ('Wing flaps — serials T20608362 and on',
    '0–10° <140 · 10–20° <120 · 20–40° <100 KIAS'),
 ]),
 ('BEFORE LANDING', [
   ('Passenger seats', 'AS FAR FORWARD AS PRACTICAL'),
   ('Pilot and passenger seat backs', 'MOST UPRIGHT POSITION'),
   ('Seats and seat belts', 'SECURED AND LOCKED'),
   ('Fuel selector valve', 'BOTH'),
   ('Mixture', 'RICH'),
   ('Propeller', 'HIGH RPM'),
   ('Landing / taxi lights', 'ON'),
   ('Autopilot (if installed)', 'OFF'),
   gap('อาจมีข้อถัดจาก 8 — ท้ายหน้าต้นฉบับถูกตัด'),
 ]),
 ('LANDING — NORMAL', [
   ('Airspeed', '80–90 KIAS (FLAPS UP)'),
   ('Wing flaps — serials thru T20608361', '0–10° <140 KIAS · 10–40° <100 KIAS'),
   ('Wing flaps — serials T20608362 and on',
    '0–10° <140 · 10–20° <120 · 20–40° <100 KIAS'),
   ('Airspeed', '70–80 KIAS (FLAPS DOWN)'),
   ('Trim', 'ADJUST AS DESIRED'),
   ('Touchdown', 'MAIN WHEELS FIRST'),
   ('Landing roll', 'LOWER NOSE WHEEL GENTLY'),
   ('Braking', 'MINIMUM REQUIRED'),
 ]),
 ('LANDING — SHORT FIELD', [
   ('Airspeed', '80–90 KIAS (FLAPS UP)'),
   ('Wing flaps', 'FULL (BELOW 100 KIAS)'),
   ('Airspeed', 'MAINTAIN 67 KIAS'),
   ('Power', 'REDUCE TO IDLE AS OBSTACLE CLEARED'),
   ('Trim', 'ADJUST'),
   ('Touchdown', 'MAIN WHEELS FIRST'),
   ('Brakes', 'APPLY HEAVILY'),
   ('Wing flaps', 'RETRACT FOR MAX BRAKING'),
 ]),
 ('BALKED LANDING', [
   ('Power', '39 IN. HG. AND 2500 RPM'),
   ('Mixture', 'ADJUST TO 34 GPH FUEL FLOW'),
   ('Wing flaps', 'RETRACT TO 20°'),
   ('Climb speed', '85 KIAS'),
   ('Wing flaps', 'RETRACT SLOWLY'),
   ('Cowl flaps', 'OPEN'),
 ]),
 ('AFTER LANDING', [
   ('Wing flaps', 'RETRACT'),
   ('Cowl flaps', 'OPEN'),
 ]),
 ('SECURING AIRPLANE', [
   ('Parking brake', 'SET'),
   ('Throttle', 'IDLE'),
   ('Electrical equipment · avionics master · autopilot', 'OFF'),
   ('Mixture', 'IDLE CUT OFF (PULLED FULL OUT)'),
   ('Ignition switch', 'OFF'),
   ('Master switch', 'OFF'),
   ('Control lock', 'INSTALL'),
   ('Fuel selector valve', 'LEFT OR RIGHT (PREVENT CROSS FEED)'),
   ('Cowl flaps', 'CLOSED'),
 ]),
]


EMERGENCY = [
 ('AIRSPEEDS — EMERGENCY OPERATION', [
   ('Engine failure after takeoff — flaps up / down', '85 / 75 KIAS'),
   ('Maneuvering speed — 3,600 / 2,950 / 2,300 lb', '125 / 120 / 106 KIAS'),
   ('Maximum glide — 3,600 / 3,200 / 2,800 lb', '80 / 75 / 70 KIAS'),
   ('Precautionary landing with engine power', '75 KIAS'),
   ('Landing without engine power — flaps up / down', '85 / 75 KIAS'),
   ('Emergency descent — smooth air', '182 KIAS'),
   ('Emergency descent — rough air, 3,600 / 2,950 / 2,300 lb', '125 / 120 / 106 KIAS'),
 ]),
 ('⚠ ENGINE FAILURE DURING TAKEOFF ROLL', [
   ('⚠ Throttle', 'IDLE'),
   ('⚠ Brakes', 'APPLY'),
   ('Wing flaps', 'RETRACT'),
   ('Mixture', 'IDLE CUT OFF'),
   ('Ignition switch', 'OFF'),
   ('Master switch', 'OFF'),
 ]),
 ('⚠ ENGINE FAILURE IMMEDIATELY AFTER TAKEOFF', [
   ('⚠ Airspeed', '85 KIAS FLAPS UP · 75 KIAS FLAPS DOWN'),
   ('Mixture', 'IDLE CUT OFF'),
   ('Fuel selector valve', 'PUSH DOWN AND ROTATE TO OFF'),
   ('Ignition switch', 'OFF'),
   ('Wing flaps', 'AS REQUIRED (40° RECOMMENDED)'),
   ('Master switch', 'OFF'),
   ('Cabin door', 'UNLATCH'),
   ('Land', 'STRAIGHT AHEAD'),
 ]),
 ('⚠ ENGINE FAILURE DURING FLIGHT (RESTART)', [
   ('⚠ Airspeed', '80 KIAS'),
   ('⚠ Fuel selector valve', 'BOTH'),
   ('⚠ Auxiliary fuel pump switch', 'ON'),
   ('Engine power', 'RESTORED'),
   ('Mixture', 'RICH (IF RESTART DOES NOT OCCUR)'),
   ('Ignition switch', 'CHECK BOTH (OR START IF PROP STOPPED)'),
   ('Auxiliary fuel pump switch', 'OFF'),
   ('If fuel flow drops to zero', 'RETURN AUX PUMP SWITCH TO ON'),
 ]),
 ('EMERGENCY LANDING WITHOUT ENGINE POWER', [
   ('Passenger seats', 'AS FAR FORWARD AS PRACTICAL'),
   ('Passenger seat backs', 'MOST UPRIGHT POSITION'),
   ('Seats and seat belts', 'SECURE'),
   ('Airspeed', '85 KIAS FLAPS UP · 75 KIAS FLAPS DOWN'),
   ('Mixture', 'IDLE CUT OFF'),
   ('Fuel selector valve', 'PUSH DOWN AND ROTATE TO OFF'),
   ('Ignition switch', 'OFF'),
   ('Wing flaps', 'AS REQUIRED (40° RECOMMENDED)'),
   ('Master switch', 'OFF WHEN LANDING IS ASSURED'),
   ('Doors', 'UNLATCH PRIOR TO TOUCHDOWN'),
   ('Touchdown', 'SLIGHTLY TAIL LOW'),
   ('Brakes', 'APPLY HEAVILY'),
 ]),
 ('PRECAUTIONARY LANDING WITH ENGINE POWER', [
   ('Passenger seats', 'AS FAR FORWARD AS PRACTICAL'),
   ('Passenger seat backs', 'MOST UPRIGHT POSITION'),
   ('Seats and seat belts', 'SECURE'),
   ('Airspeed', '85 KIAS'),
   ('Wing flaps', '20°'),
   gap('ข้อ 6 ถึง 8 — ท้ายหน้าต้นฉบับถูกตัด'),
   ('Airspeed', '75 KIAS'),
   ('Master switch', 'OFF'),
   ('Doors', 'UNLATCH PRIOR TO TOUCHDOWN'),
   ('Touchdown', 'SLIGHTLY TAIL LOW'),
   ('Ignition switch', 'OFF'),
   ('Mixture', 'IDLE CUT OFF'),
   ('Brakes', 'APPLY HEAVILY'),
 ]),
 ('DITCHING', [
   ('Radio', 'MAYDAY ON 121.5 MHz · SQUAWK 7700'),
   ('Heavy objects in baggage area', 'SECURE OR JETTISON'),
   ('Passenger seats', 'AS FAR FORWARD AS PRACTICAL'),
   ('Passenger seat backs', 'MOST UPRIGHT POSITION'),
   ('Seats and seat belts', 'SECURE'),
   ('Wing flaps', '40°'),
   ('Power', 'ESTABLISH 300 FT/MIN DESCENT AT 70 KIAS'),
   ('If no power available', '85 KIAS FLAPS UP · 80 KIAS FLAPS 10°'),
   ('Approach — high wind / heavy seas', 'INTO THE WIND'),
   ('Approach — light wind / heavy swells', 'PARALLEL TO SWELLS'),
   ('Cabin doors', 'UNLATCH'),
   ('Touchdown', 'LEVEL ATTITUDE AT 300 FT/MIN DESCENT'),
   ('Face', 'CUSHION AT TOUCHDOWN WITH FOLDED COAT'),
   gap('ข้อ 12 เป็นต้นไป (ELT ฯลฯ) — ท้ายหน้าต้นฉบับถูกตัด'),
 ]),
 ('FIRE — DURING START ON GROUND', [
   ('⚠ Ignition switch', 'START · CONTINUE CRANKING'),
   ('If engine starts — power', '1800 RPM FOR A FEW MINUTES'),
   ('If engine starts — engine', 'SHUTDOWN AND INSPECT'),
   ('⚠ If engine fails to start — ignition switch', 'START · CONTINUE CRANKING'),
   ('⚠ Throttle', 'FULL OPEN'),
   ('⚠ Mixture', 'IDLE CUT OFF'),
   ('⚠ Fuel selector valve', 'PUSH DOWN AND ROTATE TO OFF'),
   ('⚠ Auxiliary fuel pump switch', 'OFF'),
   ('Fire extinguisher', 'OBTAIN'),
   ('Engine', 'SECURE — MASTER OFF · IGNITION OFF'),
   ('Parking brake', 'RELEASE'),
   ('Airplane', 'EVACUATE'),
   ('Fire', 'EXTINGUISH — EXTINGUISHER / BLANKET / DIRT'),
   ('Fire damage', 'INSPECT BEFORE FURTHER FLIGHT'),
 ]),
 ('⚠ ENGINE FIRE IN FLIGHT', [
   gap('ข้อ 1 ถึง 4 — ท้ายหน้าต้นฉบับถูกตัด'),
   ('Cabin heat and air', 'OFF (EXCEPT OVERHEAD VENTS)'),
   ('Airspeed', '110 KIAS · INCREASE IF FIRE NOT OUT'),
   ('Forced landing', 'EXECUTE'),
 ]),
 ('⚠ ELECTRICAL FIRE IN FLIGHT', [
   ('⚠ Master switch', 'OFF'),
   ('⚠ Vents / cabin air / heat', 'CLOSED'),
   ('⚠ Fire extinguisher', 'ACTIVATE'),
   ('⚠ Avionics master switch', 'OFF'),
   ('⚠ All other switches (except ignition)', 'OFF'),
   ('After discharging extinguisher', 'VENTILATE THE CABIN'),
   ('Vents / cabin air / heat', 'OPEN WHEN FIRE IS OUT'),
 ]),
 ('⚠ CABIN FIRE', [
   ('⚠ Master switch', 'OFF'),
   ('⚠ Vents / cabin air / heat', 'CLOSED (AVOID DRAFTS)'),
   ('⚠ Fire extinguisher', 'ACTIVATE'),
   ('Vents / cabin air', 'OPEN WHEN FIRE IS OUT'),
   ('Land', 'AS SOON AS POSSIBLE · INSPECT'),
 ]),
 ('⚠ WING FIRE', [
   ('⚠ Landing / taxi light switches', 'OFF'),
   ('⚠ Navigation light switch', 'OFF'),
   ('⚠ Strobe light switch', 'OFF'),
   ('⚠ Pitot heat switch', 'OFF'),
   ('Sideslip', 'KEEP FLAMES AWAY FROM FUEL TANK'),
   ('Land', 'AS SOON AS POSSIBLE · FLAPS ONLY AS NEEDED'),
 ]),
 ('INADVERTENT ICING ENCOUNTER', [
   ('⚠ Pitot heat switch', 'ON'),
   ('⚠ Turn back or change altitude', 'LESS CONDUCIVE OAT'),
   ('⚠ Cabin heat and defrost controls', 'FULL OUT'),
   ('Engine speed', 'INCREASE · CYCLE TO 2200 RPM IF VIBRATION'),
   ('Induction air filter icing', 'REGAIN MP BY INCREASING THROTTLE'),
   ('Landing', 'PLAN FOR NEAREST AIRPORT'),
   gap('ข้อ 7 ถึง 9 — ท้ายหน้าต้นฉบับถูกตัด'),
   ('Approach', '95–100 KIAS FLAPS 20° · 110–120 KIAS FLAPS 0–10°'),
   ('Landing', 'MAIN WHEELS FIRST · AVOID SLOW HIGH FLARE'),
   ('Missed approach', 'AVOID · IF REQUIRED 100 KIAS · FLAPS 10° STEPS'),
 ]),
 ('STATIC SOURCE BLOCKAGE', [
   ('⚠ Static pressure alternate source valve', 'PULL ON'),
   ('Heat and air valves', 'PULL ON'),
   ('Vents', 'CLOSED'),
   ('Airspeed', 'CONSULT POH SECTION 5 CALIBRATION'),
   ('Altitude', 'CONSULT POH SECTION 5 CALIBRATION'),
 ]),
 ('EXCESSIVE FUEL VAPOR', [
   ('⚠ Auxiliary fuel pump switch', 'ON'),
   ('Mixture', 'RESET AS REQUIRED'),
   ('Fuel selector valve', 'SELECT OPPOSITE TANK IF SYMPTOMS CONTINUE'),
   ('Auxiliary fuel pump switch', 'OFF AFTER FLOW STABILISES'),
 ]),
 ('LANDING WITH A FLAT MAIN TIRE', [
   ('Approach', 'NORMAL'),
   ('Wing flaps — serials thru T20608361', '0–10° <140 KIAS · 10–40° <100 KIAS'),
   ('Wing flaps — serials T20608362 and on',
    '0–10° <140 · 10–20° <120 · 20–40° <100 KIAS'),
   ('Touchdown', 'GOOD MAIN TIRE FIRST · HOLD FLAT TIRE OFF'),
   ('Directional control', 'BRAKE ON GOOD WHEEL AS REQUIRED'),
 ]),
 ('LANDING WITH A FLAT NOSE TIRE', [
   gap('ทั้งหัวข้อ — ท้ายหน้าต้นฉบับถูกตัด ไม่มีข้อความให้ถอด'),
 ]),
 ('ELECTRICAL — AMMETER SHOWS EXCESSIVE RATE OF CHARGE', [
   ('Alternator', 'OFF'),
   ('Nonessential electrical equipment', 'OFF'),
   ('Flight', 'TERMINATE AS SOON AS PRACTICAL'),
   ('Note', 'COMPASS DEVIATION UP TO 25° WITH ALT OFF'),
 ]),
 ('ELECTRICAL — LOW VOLTAGE ANNUNCIATOR (VOLTS) IN FLIGHT', [
   ('Avionics master switch', 'OFF'),
   ('Alternator circuit breaker (ALT FLD)', 'CHECK IN'),
   ('Master switch', 'OFF (BOTH SIDES)'),
   ('Master switch', 'ON'),
   ('Low voltage annunciator (VOLTS)', 'CHECK OFF'),
   ('Avionics master switch', 'ON'),
   ('If VOLTS illuminates again — alternator', 'OFF'),
   ('Nonessential radio and electrical equipment', 'OFF'),
   ('Flight', 'TERMINATE AS SOON AS PRACTICAL'),
 ]),
 ('EMERGENCY DESCENT — SMOOTH AIR', [
   ('Seats and seat belts', 'SECURE'),
   ('Throttle', 'IDLE'),
   gap('ข้อ 3 เป็นต้นไป — ท้ายหน้าต้นฉบับถูกตัด'),
 ]),
 ('EMERGENCY DESCENT — ROUGH AIR', [
   ('Seats and seat belts', 'SECURE'),
   ('Throttle', 'IDLE'),
   ('Propeller', 'HIGH RPM'),
   ('Mixture', 'FULL RICH'),
   ('Wing flaps', 'UP'),
   ('Airspeed — 3,600 / 2,950 / 2,300 lb', '125 / 120 / 106 KIAS'),
 ]),
 ('VACUUM SYSTEM FAILURE (L VAC or VAC R)', [
   ('⚠ Vacuum gage', 'CHECK WITHIN NORMAL LIMITS'),
   gap('ข้อ 2 เป็นต้นไป — ท้ายหน้าต้นฉบับถูกตัด'),
   ('If outside limits', 'PARTIAL PANEL PROCEDURES MAY BE REQUIRED'),
 ]),
]
